#!/usr/bin/python3

import requests
from bs4 import BeautifulSoup
import sys

# nvim has problems with showing polish characters on execution
def decodePolish(text):
    polish = {"Ą":"A","Ć":"C",
"Ę":"E","Ł":"L","Ń":"N","Ó":"O",
"Ś":"S","Ż":"Z","Ź":"Z","ą":"a",
"ć":"c","ę":"e","ł":"l","ń":"n",
"ó":"o","ś":"s","ż":"z","ź":"z"}
    for x in polish.keys():
        text = str.replace(text,x,polish[x])
    return text

word = sys.argv[1]

pagehtml = requests.get("https://sjp.pl/" + word).text
soup = BeautifulSoup(pagehtml, 'html.parser')

try:
    allowable = soup.find_all('p', attrs={'style':'color: #555;'})[0].contents[0]
    definition = soup.find_all('p', attrs={'style':'margin: .5em 0; font: medium/1.4 sans-serif; max-width: 32em; '})[0].contents
except:
    allowable = False

if(allowable != False):
    print(decodePolish(word))
    print(allowable)
    print('')
    for line in definition:
        if str(line) != '<br/>':
            print(decodePolish(line))
    print('')
else:
    print(decodePolish(word))
    print("Nie występuje w słowniku")
    print('')
